### ISSUE TITLE
Steps to run this locally

### ISSUE THREAD

**Issue by edjustice** [shoaibrayeen/Chatbot#1]
Hi Shoaib, could you add stepsin the Read.ME  to run this locally on our machine.

**Comment by shoaibrayeen** [comment]
- I'll update it soon!
- Thanks for reminding me!
- If you want, download the repository and run app.py.

**Comment by edjustice** [comment]
![image](https://user-images.githubusercontent.com/41233668/68550759-e62c7700-042b-11ea-9de8-4b51b5671b1b.png)

@shoaibrayeen could you have a look at this bug. It should be localhost:5000 instead of this link. Because using this link it doesnt open when I run python app.py

**Comment by edjustice** [comment]
Also I am not getting a response object for the query I run while interacting with the bot
![image](https://user-images.githubusercontent.com/41233668/68550788-33a8e400-042c-11ea-9edf-ff7800eb5cc2.png)

**Comment by edjustice** [comment]
So is this an issue right now?
